const king = '<div class="piece" id="king"><div>&#9812</div></div>'
const queen = '<div class="piece" id="queen"><div>&#9813</div></div>'
const bishop = '<div class="piece" id="bishop"><div>&#9815</div></div>'
const knight = '<div class="piece" id="knight"><div>&#9816</div></div>'
const rook = '<div class="piece" id="rook"><div>&#9814</div></div>'
const pawn = '<div class="piece" id="pawn"><div>&#9817</div></div>'