const w_king = '<div class="piece white" id="king">&#9812</div>'
const w_queen = '<div class="piece white" id="queen">&#9813</div>'
const w_bishop = '<div class="piece white" id="bishop">&#9815</div>'
const w_knight = '<div class="piece white" id="knight">&#9816</div>'
const w_rook = '<div class="piece white" id="rook">&#9814</div>'
const w_pawn = '<div class="piece white" id="pawn">&#9817</div>'

const b_king = '<div class="piece black" id="king">&#9812</div>'
const b_queen = '<div class="piece black" id="queen">&#9813</div>'
const b_bishop = '<div class="piece black" id="bishop">&#9815</div>'
const b_knight = '<div class="piece black" id="knight">&#9816</div>'
const b_rook = '<div class="piece black" id="rook">&#9814</div>'
const b_pawn = '<div class="piece black" id="pawn">&#9817</div>'